spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/newnumbercoil
#      uri: mongodb://10.88.1.35:27017/testnumbercoil
      uri: mongodb://localhost:27017/testnumbercoil
logging:
  file:
    path: springboot.log
  level:
    com.cisdi.numbercoil: debug

server:
  port: 8181

data:
  condition:
    coilnoparent: 母卷号
    steelgrade: 钢种号
    coilno: 出钢记号（牌号）
    stripthick: 带钢厚度
    stripwidth: 带钢宽度
    stripcrown: 带钢凸度
    striplength: 带钢长度
    innerdia: 钢卷内径
    outerdia: 钢卷外径
    stripweight: 卷重
    producetime: 生产日期
    finishtime: 结束日期
    standard: 质量标准（国标、行业、厂标）
    slabthick: 板坯厚度
    thi_slab_thick: 额定板坯厚度
    slabwidth: 板坯宽度
    slabwidthhead: 板坯头部宽度
    slabwidthtail: 板坯尾部宽度
    slablength: 板坯长度
    slabweight: 板坯重量
    isdegradation: 是否混交坯（炉次降级）
    fmaimthick: 带钢目标厚度
    fmaimthickhigh: 带钢目标厚度上限
    fmaimthicklow: 带钢目标厚度下限
    fmaimwidth: 带钢目标宽度
    fmaimwidthhigh: 带钢目标宽度上限
    fmaimwidthlow: 带钢目标宽度下限
    fmaimcrown: 带钢目标凸度
    fmaimcrownhigh: 带钢目标凸度上限
    fmaimcrownlow: 带钢目标凸度下限
    fmaimflatness: 带钢目标平直度
    fmaimflatnesshigh: 带钢目标平直度上限
    fmaimflatnesslow: 带钢目标平直度下限
    aimfdt: 带钢目标终轧温度
    aimfdthigh: 带钢目标终轧温度上限
    aimfdtlow: 带钢目标终轧温度下限
    aimct: 带钢目标卷取温度
    aimcthigh: 带钢目标卷取温上限
    aimctlow: 带钢目标卷取温下限
    curve_fmthick: 带钢实测厚度
    curve_fmwidth: 带钢实测宽度
    curve_crownc10: 带钢实测凸度（C10）
    curve_crownc20: 带钢实测凸度（C20）
    curve_crownc50: 带钢实测凸度（C50）
    curve_crownc100: 带钢实测凸度（C100）
    curve_wedgec25: 带钢实测楔形(C25)
    curve_wedgec100: 带钢实测楔形(C100)
    curve_fdt: 带钢实测终轧温度
    curve_ct: 带钢实测卷取温度
    symflat_accuracy_head: 平直度头100m对称性精度
    asymflat_accuracy_head: 平直度头100m非对称性精度
    symflat_accuracy_tail: 平直度尾100m对称性精度
    asymflat_accuracy_tail: 平直度尾100m非对称性精度
    wedge_head_part: 楔形头段精度
    wedge_mid_part: 楔形中段精度
    wedge_tail_part: 楔形尾段精度
    wedge_meanhead_part: 楔形头段绝对值平均值
    wedge_meanmid_part: 楔形中段绝对值平均值
    wedge_meantail_part: 楔形尾段绝对值平均值
    wedge_accuracy_all: 楔形全长精度
    wedge_mean_all: 楔形全长均值
    wedge_variance: 楔形全长方差
    crown_head_part: 凸度头段精度
    crown_mid_part: 凸度中段精度
    crown_tail_part: 凸度尾段精度
    crown_meanhead_part: 凸度头段均值
    crown_meanmid_part: 凸度中段均值
    crown_meantail_part: 凸度尾段均值
    crown_accuracy_all: 凸度全长精度
    crown_mean_all: 凸度全长均值
    crown_range_all: 凸度全长极差值
    thick_accuracy_all: 厚度全长精度
    thick_accuracy_head: 厚度分段精度头部
    thick_accuracy_body: 厚度分段精度中部
    thick_accuracy_tail: 厚度分段精度尾部
    width_accuracy_all: 宽度全长精度
    width_accuracy_head: 宽度分段精度头部
    width_accuracy_body: 宽度分段精度中部
    width_accuracy_tail: 宽度分段精度尾部
    width_range_head: 宽度头部极差
    width_range_body: 宽度本体偏差
    width_range_tail: 宽度尾部极差
    RT2_mean_all: RT2全长均值
    RT2_range_all: RT2全长极差值
    RT7_accuracy_all: FT7全长精度
    RT7_accuracy_head: FT7分段精度头部
    RT7_accuracy_body: FT7分段精度中部
    RT7_accuracy_tail: FT7分段精度尾部
    RT7_range_all: FT7全长极差值
    RT7_mean_all: FT7全长均值
    RT7_mean_head: FT7分段均值头部
    RT7_mean_body: FT7分段均值中部
    RT7_mean_tail: FT7分段均值尾部
    CT_accuracy_all: CT全长精度
    CT_accuracy_head: CT分段精度头部
    CT_accuracy_body: CT分段精度中部
    CT_accuracy_tail: CT分段精度尾部
    CT_range_all: CT全长极差值
    CT_mean_all: CT全长均值
    CT_mean_head: CT分段均值头部
    CT_mean_body: CT分段均值中部
    CT_mean_tail: CT分段均值尾部
    CT_range_head: CT头部极差
    CT_range_tail: CT尾部极差
    CT_range_body: CT中部极差
    CS_mean_all: CS全长均值
    yield_strength_max: 屈服上限
    yield_strength_min: 屈服下限
    tensile_strength_max: 抗拉上限
    tensile_strength_min: 抗拉下限
    elongation: 延伸率
    break_el_max: 断裂延伸率上限
    break_el_aim: 断裂延伸率目标
    break_el_min: 断裂延伸率下限
    impact_aver_min: 冲击功均值下限
    impact_val_min: 冲击功单值下限
    hardness: 硬度
    bot_ys_1: 下屈服强度_1
    top_ys_1: 上屈服强度_1
    yield_rt_1: 延伸强度_1
    ts_1: 抗拉强度1
    el_1: 伸长率1
    redu_area: 断面收缩率
    homo_el: 均匀延伸率
    bot_ys_2: 下屈服强度_2
    top_ys_2: 上屈服强度_2
    ts_2: 抗拉强度2
    el_2: 伸长率2
    bot_ys_3: 下屈服强度_3
    top_ys_3: 上屈服强度_3
    ts_3: 抗拉强度3
    el_3: 伸长率3
    magnetic: 磁感度
    surfdefect1_type: 表面缺陷类型1
    surfdefect1_amount: 表面缺陷类型1数量
    surfdefect1_ratio: 表面缺陷类型1比率
    surfdefect1_location: 表面缺陷类型1位置
    surfdefect2_type: 表面缺陷类型2
    surfdefect2_amount: 表面缺陷类型2数量
    surfdefect2_ratio: 表面缺陷类型2比率
    surfdefect2_location: 表面缺陷类型2位置
    surfdefect3_type: 表面缺陷类型3
    surfdefect3_amount: 表面缺陷类型3数量
    surfdefect3_ratio: 表面缺陷类型3比率
    surfdefect3_location: 表面缺陷类型3位置
    surfdefect4_type: 表面缺陷类型4
    SG_STD: 检验标准
    COMPLEX_DECIDE_CODE: 质量终判结果
    o_material_adhesion: 氧化铁皮附着力
    rmdesc_temp: 粗轧除鳞后温度
    ssp_use: SSP使用标志
    ssp_act_current: SSP电机实际电流
    ssp_act_exitwidth: SSP出口实测热宽度
    rm1_pass_total: 粗轧轧制道次1
    rm2_pass_total: 粗轧轧制道次2
    rm3_pass_total: 粗轧轧制道次3
    rm4_pass_total: 粗轧轧制道次4
    rm5_pass_total: 粗轧轧制道次5
    rm6_pass_total: 粗轧轧制道次6
    rm7_pass_total: 粗轧轧制道次7
    rmr1_act_rollgap: 粗轧R1每道次实测辊缝值
    rmr1_act_force: 粗轧R1每道次实测轧制力
    rmr1_act_power: 粗轧R1每道次实际电机功率
    rmr1_act_current: 粗轧R1每道次轧机电流
    rmr1_act_rollspeed: "粗轧R1每道次工作辊实际线速度"
    rmr1_descflag: 粗轧R1每道次除鳞标志
    rmr11_act_extemp: 粗轧R11每道次出口温度
    rmr12_act_extemp: 粗轧R12每道次出口温度
    rmr13_act_extemp: 粗轧R13每道次出口温度
    rmr14_act_extemp: 粗轧R14每道次出口温度
    rmr15_act_extemp: 粗轧R15每道次出口温度
    rmr16_act_extemp: 粗轧R16每道次出口温度
    rmr17_act_extemp: 粗轧R17每道次出口温度
    rmr21_act_rollgap: 粗轧R21每道次实测辊缝值
    rmr22_act_rollgap: 粗轧R22每道次实测辊缝值
    rmr23_act_rollgap: 粗轧R23每道次实测辊缝值
    rmr24_act_rollgap: 粗轧R24每道次实测辊缝值
    rmr25_act_rollgap: 粗轧R25每道次实测辊缝值
    rmr26_act_rollgap: 粗轧R26每道次实测辊缝值
    rmr27_act_rollgap: 粗轧R27每道次实测辊缝值
    rmr21_act_force: 粗轧R21每道次实测轧制力
    rmr22_act_force: 粗轧R22每道次实测轧制力
    rmr23_act_force: 粗轧R23每道次实测轧制力
    rmr24_act_force: 粗轧R24每道次实测轧制力
    rmr25_act_force: 粗轧R25每道次实测轧制力
    rmr26_act_force: 粗轧R26每道次实测轧制力
    rmr27_act_force: 粗轧R27每道次实测轧制力
    rmr21_act_forceDS: 粗轧R21每道次实测轧制力传动侧
    rmr22_act_forceDS: 粗轧R22每道次实测轧制力传动侧
    rmr23_act_forceDS: 粗轧R23每道次实测轧制力传动侧
    rmr24_act_forceDS: 粗轧R24每道次实测轧制力传动侧
    rmr25_act_forceDS: 粗轧R25每道次实测轧制力传动侧
    rmr26_act_forceDS: 粗轧R26每道次实测轧制力传动侧
    rmr27_act_forceDS: 粗轧R27每道次实测轧制力传动侧
    rmr21_act_forceWS: 粗轧R21每道次实测轧制力操作侧
    rmr22_act_forceWS: 粗轧R22每道次实测轧制力操作侧
    rmr23_act_forceWS: 粗轧R23每道次实测轧制力操作侧
    rmr24_act_forceWS: 粗轧R24每道次实测轧制力操作侧
    rmr25_act_forceWS: 粗轧R25每道次实测轧制力操作侧
    rmr26_act_forceWS: 粗轧R26每道次实测轧制力操作侧
    rmr27_act_forceWS: 粗轧R27每道次实测轧制力操作侧
    rmr21_entrydescflag: 粗轧R21每道次入口除鳞标志
    rmr22_entrydescflag: 粗轧R22每道次入口除鳞标志
    rmr23_entrydescflag: 粗轧R23每道次入口除鳞标志
    rmr24_entrydescflag: 粗轧R24每道次入口除鳞标志
    rmr25_entrydescflag: 粗轧R25每道次入口除鳞标志
    rmr26_entrydescflag: 粗轧R26每道次入口除鳞标志
    rmr27_entrydescflag: 粗轧R27每道次入口除鳞标志
    rmr21_exitdescflag: 粗轧R21每道次出口除鳞标志
    rmr22_exitdescflag: 粗轧R22每道次出口除鳞标志
    rmr23_exitdescflag: 粗轧R23每道次出口除鳞标志
    rmr24_exitdescflag: 粗轧R24每道次出口除鳞标志
    rmr25_exitdescflag: 粗轧R25每道次出口除鳞标志
    rmr26_exitdescflag: 粗轧R26每道次出口除鳞标志
    rmr27_exitdescflag: 粗轧R27每道次出口除鳞标志
    rmr21_act_entemp: 粗轧R21每道次入口温度
    rmr22_act_entemp: 粗轧R22每道次入口温度
    rmr23_act_entemp: 粗轧R23每道次入口温度
    rmr24_act_entemp: 粗轧R24每道次入口温度
    rmr25_act_entemp: 粗轧R25每道次入口温度
    rmr26_act_entemp: 粗轧R26每道次入口温度
    rmr27_act_entemp: 粗轧R27每道次入口温度
    rmr21_act_extemp_1: 粗轧R21每道次出口温度-1
    rmr22_act_extemp_1: 粗轧R22每道次出口温度-1
    rmr23_act_extemp_1: 粗轧R23每道次出口温度-1
    rmr24_act_extemp_1: 粗轧R24每道次出口温度-1
    rmr25_act_extemp_1: 粗轧R25每道次出口温度-1
    rmr26_act_extemp_1: 粗轧R26每道次出口温度-1
    rmr27_act_extemp_1: 粗轧R27每道次出口温度-1
    rmr21_act_extemp_2: 粗轧R21每道次出口温度-2
    rmr22_act_extemp_2: 粗轧R22每道次出口温度-2
    rmr23_act_extemp_2: 粗轧R23每道次出口温度-2
    rmr24_act_extemp_2: 粗轧R24每道次出口温度-2
    rmr25_act_extemp_2: 粗轧R25每道次出口温度-2
    rmr26_act_extemp_2: 粗轧R26每道次出口温度-2
    rmr27_act_extemp_2: 粗轧R27每道次出口温度-2
    rme21_act_rollspeedDS: 粗轧E21每道次工作辊传动侧实际转速
    rme22_act_rollspeedDS: 粗轧E22每道次工作辊传动侧实际转速
    rme23_act_rollspeedDS: 粗轧E23每道次工作辊传动侧实际转速
    rme24_act_rollspeedDS: 粗轧E24每道次工作辊传动侧实际转速
    rme25_act_rollspeedDS: 粗轧E25每道次工作辊传动侧实际转速
    rme26_act_rollspeedDS: 粗轧E26每道次工作辊传动侧实际转速
    rme27_act_rollspeedDS: 粗轧E27每道次工作辊传动侧实际转速
    rme21_act_rollspeedOS: 粗轧E21每道次工作辊操作侧实际转速
    rme22_act_rollspeedOS: 粗轧E22每道次工作辊操作侧实际转速
    rme23_act_rollspeedOS: 粗轧E23每道次工作辊操作侧实际转速
    rme24_act_rollspeedOS: 粗轧E24每道次工作辊操作侧实际转速
    rme25_act_rollspeedOS: 粗轧E25每道次工作辊操作侧实际转速
    rme26_act_rollspeedOS: 粗轧E26每道次工作辊操作侧实际转速
    rme27_act_rollspeedOS: 粗轧E27每道次工作辊操作侧实际转速
    rme21_act_rollgap: 粗轧E21每道次实测辊缝值
    rme22_act_rollgap: 粗轧E22每道次实测辊缝值
    rme23_act_rollgap: 粗轧E23每道次实测辊缝值
    rme24_act_rollgap: 粗轧E24每道次实测辊缝值
    rme25_act_rollgap: 粗轧E25每道次实测辊缝值
    rme26_act_rollgap: 粗轧E26每道次实测辊缝值
    rme27_act_rollgap: 粗轧E27每道次实测辊缝值
    rme21_act_forceDS: 粗轧E21每道次压头传动侧实测轧制力
    rme22_act_forceDS: 粗轧E22每道次压头传动侧实测轧制力
    rme23_act_forceDS: 粗轧E23每道次压头传动侧实测轧制力
    rme24_act_forceDS: 粗轧E24每道次压头传动侧实测轧制力
    rme25_act_forceDS: 粗轧E25每道次压头传动侧实测轧制力
    rme26_act_forceDS: 粗轧E26每道次压头传动侧实测轧制力
    rme27_act_forceDS: 粗轧E27每道次压头传动侧实测轧制力
    rme21_act_forceOS: 粗轧E21每道次压头操作侧实测轧制力
    rme22_act_forceOS: 粗轧E22每道次压头操作侧实测轧制力
    rme23_act_forceOS: 粗轧E23每道次压头操作侧实测轧制力
    rme24_act_forceOS: 粗轧E24每道次压头操作侧实测轧制力
    rme25_act_forceOS: 粗轧E25每道次压头操作侧实测轧制力
    rme26_act_forceOS: 粗轧E26每道次压头操作侧实测轧制力
    rme27_act_forceOS: 粗轧E27每道次压头操作侧实测轧制力
    rme21_act_currentDS: 粗轧E21每道次电机电流传动侧
    rme22_act_currentDS: 粗轧E22每道次电机电流传动侧
    rme23_act_currentDS: 粗轧E23每道次电机电流传动侧
    rme24_act_currentDS: 粗轧E24每道次电机电流传动侧
    rme25_act_currentDS: 粗轧E25每道次电机电流传动侧
    rme26_act_currentDS: 粗轧E26每道次电机电流传动侧
    rme27_act_currentDS: 粗轧E27每道次电机电流传动侧
    rme21_act_currentOS: 粗轧E21每道次电机电流操作侧
    rme22_act_currentOS: 粗轧E22每道次电机电流操作侧
    rme23_act_currentOS: 粗轧E23每道次电机电流操作侧
    rme24_act_currentOS: 粗轧E24每道次电机电流操作侧
    rme25_act_currentOS: 粗轧E25每道次电机电流操作侧
    rme26_act_currentOS: 粗轧E26每道次电机电流操作侧
    rme27_act_currentOS: 粗轧E27每道次电机电流操作侧
    E2_loadcell_OS_rollforce: E2操作侧轧制力
    E2_loadcell_DS_rollforce: E2传动侧轧制力
    trbwidth: 中间坯实测宽度
    mid_slab_thick_min: 中间坯厚度下限值
    mid_slab_thick_max: 中间坯厚度上限值
    trbcenterDev: 中间坯实测中心线偏差
    fm_descflag: 精轧除鳞使用标志
    fmentertemp: 飞剪高温计实测温度
    f1_dummy: F1使用状态
    f2_dummy: F2使用状态
    f3_dummy: F3使用状态
    f4_dummy: F4使用状态
    f5_dummy: F5使用状态
    f6_dummy: F6使用状态
    f7_dummy: F7使用状态
    f1_act_rollgap: F1辊缝值
    f2_act_rollgap: F2辊缝值
    f3_act_rollgap: F3辊缝值
    f4_act_rollgap: F4辊缝值
    f5_act_rollgap: F5辊缝值
    f6_act_rollgap: F6辊缝值
    f7_act_rollgap: F7辊缝值
    f1_act_rollgapDS: F1实际辊缝值传动侧
    f2_act_rollgapDS: F2实际辊缝值传动侧
    f3_act_rollgapDS: F3实际辊缝值传动侧
    f4_act_rollgapDS: F4实际辊缝值传动侧
    f5_act_rollgapDS: F5实际辊缝值传动侧
    f6_act_rollgapDS: F6实际辊缝值传动侧
    f7_act_rollgapDS: F7实际辊缝值传动侧
    f1_act_rollgapWS: F1实际辊缝值操作侧
    f2_act_rollgapWS: F2实际辊缝值操作侧
    f3_act_rollgapWS: F3实际辊缝值操作侧
    f4_act_rollgapWS: F4实际辊缝值操作侧
    f5_act_rollgapWS: F5实际辊缝值操作侧
    f6_act_rollgapWS: F6实际辊缝值操作侧
    f7_act_rollgapWS: F7实际辊缝值操作侧
    f1_act_rollspeed: F1工作辊实际线速度
    f2_act_rollspeed: F2工作辊实际线速度
    f3_act_rollspeed: F3工作辊实际线速度
    f4_act_rollspeed: F4工作辊实际线速度
    f5_act_rollspeed: F5工作辊实际线速度
    f6_act_rollspeed: F6工作辊实际线速度
    f7_act_rollspeed: F7工作辊实际线速度
    f1_act_forceDS: F1传动侧轧制力
    f2_act_forceDS: F2传动侧轧制力
    f3_act_forceDS: F3传动侧轧制力
    f4_act_forceDS: F4传动侧轧制力
    f5_act_forceDS: F5传动侧轧制力
    f6_act_forceDS: F6传动侧轧制力
    f7_act_forceDS: F7传动侧轧制力
    f1_act_forceWS: F1操作侧轧制力
    f2_act_forceWS: F2操作侧轧制力
    f3_act_forceWS: F3操作侧轧制力
    f4_act_forceWS: F4操作侧轧制力
    f5_act_forceWS: F5操作侧轧制力
    f6_act_forceWS: F6操作侧轧制力
    f7_act_forceWS: F7操作侧轧制力
    f1_act_bendforce: F1实际弯辊力
    f2_act_bendforce: F2实际弯辊力
    f3_act_bendforce: F3实际弯辊力
    f4_act_bendforce: F4实际弯辊力
    f5_act_bendforce: F5实际弯辊力
    f6_act_bendforce: F6实际弯辊力
    f7_act_bendforce: F7实际弯辊力
    f1_act_shiftpos: F1实际窜辊位置
    f2_act_shiftpos: F2实际窜辊位置
    f3_act_shiftpos: F3实际窜辊位置
    f5_act_shiftpos: F5实际窜辊位置
    f6_act_shiftpos: F6实际窜辊位置
    f1_act_current: F1电机电流
    f2_act_current: F2电机电流
    f3_act_current: F3电机电流
    f4_act_current: F4电机电流
    f5_act_current: F5电机电流
    f6_act_current: F6电机电流
    f7_act_current: F7电机电流
    f1_act_loopergangle: F1活套角度
    f2_act_loopergangle: F2活套角度
    f3_act_loopergangle: F3活套角度
    f4_act_loopergangle: F4活套角度
    f5_act_loopergangle: F5活套角度
    f6_act_loopergangle: F6活套角度
    f1_act_tension: F1活套张力
    f2_act_tension: F2活套张力
    f3_act_tension: F3活套张力
    f4_act_tension: F4活套张力
    f5_act_tension: F5活套张力
    f6_act_tension: F6活套张力
    f1_torque: F1轧机转矩
    f2_torque: F2轧机转矩
    f3_torque: F3轧机转矩
    f4_torque: F4轧机转矩
    f5_torque: F5轧机转矩
    f6_torque: F6轧机转矩
    f7_torque: F7轧机转矩
    f1_SIS: F1的咬钢信号
    f2_SIS: F2的咬钢信号
    f3_SIS: F3的咬钢信号
    f4_SIS: F4的咬钢信号
    f5_SIS: F5的咬钢信号
    f6_SIS: F6的咬钢信号
    f7_SIS: F7的咬钢信号
    f1_act_possideguideDS: F1精轧机架间传动侧侧导板位置
    f2_act_possideguideDS: F2精轧机架间传动侧侧导板位置
    f3_act_possideguideDS: F3精轧机架间传动侧侧导板位置
    f4_act_possideguideDS: F4精轧机架间传动侧侧导板位置
    f5_act_possideguideDS: F5精轧机架间传动侧侧导板位置
    f6_act_possideguideDS: F6精轧机架间传动侧侧导板位置
    f7_act_possideguideDS: F7精轧机架间传动侧侧导板位置
    f1_act_possideguideOS: F1精轧机架间操作侧侧导板位置
    f2_act_possideguideOS: F2精轧机架间操作侧侧导板位置
    f3_act_possideguideOS: F3精轧机架间操作侧侧导板位置
    f4_act_possideguideOS: F4精轧机架间操作侧侧导板位置
    f5_act_possideguideOS: F5精轧机架间操作侧侧导板位置
    f6_act_possideguideOS: F6精轧机架间操作侧侧导板位置
    f7_act_possideguideOS: F7精轧机架间操作侧侧导板位置
    f2_intercool_topflow: F2精轧机架间上冷却水流量
    f3_intercool_topflow: F3精轧机架间上冷却水流量
    f4_intercool_topflow: F4精轧机架间上冷却水流量
    f5_intercool_topflow: F5精轧机架间上冷却水流量
    f6_intercool_topflow: F6精轧机架间上冷却水流量
    f2_intercool_botflow: F2精轧机架间下冷却水流量
    f3_intercool_botflow: F3精轧机架间下冷却水流量
    f4_intercool_botflow: F4精轧机架间下冷却水流量
    f5_intercool_botflow: F5精轧机架间下冷却水流量
    f6_intercool_botflow: F6精轧机架间下冷却水流量
    f1_rollcoolflow: F1精轧机工作辊冷却水流量
    f2_rollcoolflow: F2精轧机工作辊冷却水流量
    f3_rollcoolflow: F3精轧机工作辊冷却水流量
    f4_rollcoolflow: F4精轧机工作辊冷却水流量
    f5_rollcoolflow: F5精轧机工作辊冷却水流量
    f6_rollcoolflow: F6精轧机工作辊冷却水流量
    f7_rollcoolflow: F7精轧机工作辊冷却水流量
    cs_coolvalve_status: 冷却区各集管开启状态
    cs_sidevalve_status: 侧喷阀门开启状态
    cs_faultvalve_status: 故障阀状态
    dc_no: 卷取机号
    dc_pr_tension: 夹送辊张力
    dc1_prt_speed: C1上夹送辊速度
    dc1_prb_speed: C1下夹送辊速度
    dc2_prt_speed: C2上夹送辊速度
    dc2_prb_speed: C2下夹送辊速度
    dc3_prt_speed: C3上夹送辊速度
    dc3_prb_speed: C3下夹送辊速度
    dc_md_tension: 卷筒张力
    dc1_md_speed: C1卷筒速度
    dc2_md_speed: C2卷筒速度
    dc3_md_speed: C3卷筒速度
    fur_chargetemp: 入炉温度
    fur_chargetime: 装炉时刻
    fur_extracttime: 出炉时刻
    fur_intime: 在炉时间
    fur_intime_preheat: 在预热段时间
    fur_intime_heat1: 在一加段时间
    fur_intime_heat2: 在二加段时间
    fur_intime_soak: 在均热段时间
    fur_temp_preheat: 预热段出口温度
    fur_temp_heat1: 一加段出口温度
    fur_temp_heat2: 二加段出口温度
    fur_temp_soak: 均热段出口温度
    fur_exittemp: 出炉温度
    R21_SG_exitwidth: L2设定R21侧导板出口宽度
    R22_SG_exitwidth: L2设定R22侧导板出口宽度
    R23_SG_exitwidth: L2设定R23侧导板出口宽度
    R24_SG_exitwidth: L2设定R24侧导板出口宽度
    R25_SG_exitwidth: L2设定R25侧导板出口宽度
    R26_SG_exitwidth: L2设定R26侧导板出口宽度
    R27_SG_exitwidth: L2设定R27侧导板出口宽度
    R21_SG_entrywidth: L2设定R21侧导板入口宽度
    R22_SG_entrywidth: L2设定R22侧导板入口宽度
    R23_SG_entrywidth: L2设定R23侧导板入口宽度
    R24_SG_entrywidth: L2设定R24侧导板入口宽度
    R25_SG_entrywidth: L2设定R25侧导板入口宽度
    R26_SG_entrywidth: L2设定R26侧导板入口宽度
    R27_SG_entrywidth: L2设定R27侧导板入口宽度
    R1_sideguide_tension: R1侧导板压力
    R21_sideguide_tension: R21侧导板压力
    R22_sideguide_tension: R22侧导板压力
    R23_sideguide_tension: R23侧导板压力
    R24_sideguide_tension: R24侧导板压力
    R25_sideguide_tension: R25侧导板压力
    R26_sideguide_tension: R26侧导板压力
    R27_sideguide_tension: R27侧导板压力
    E21_sideguide_tension: E21侧导板压力
    E22_sideguide_tension: E22侧导板压力
    E23_sideguide_tension: E23侧导板压力
    E24_sideguide_tension: E24侧导板压力
    E25_sideguide_tension: E25侧导板压力
    E26_sideguide_tension: E26侧导板压力
    E27_sideguide_tension: E27侧导板压力
    decc: 抛钢减速度
    runoutspeed: 最大抛钢速度
    F1_agc_wssthc: F1厚度控制设定值
    F2_agc_wssthc: F2厚度控制设定值
    F3_agc_wssthc: F3厚度控制设定值
    F4_agc_wssthc: F4厚度控制设定值
    F5_agc_wssthc: F5厚度控制设定值
    F6_agc_wssthc: F6厚度控制设定值
    F7_agc_wssthc: F7厚度控制设定值
    F1_agc_wssagc: F1自动厚度控制设定值
    F2_agc_wssagc: F2自动厚度控制设定值
    F3_agc_wssagc: F3自动厚度控制设定值
    F4_agc_wssagc: F4自动厚度控制设定值
    F5_agc_wssagc: F5自动厚度控制设定值
    F6_agc_wssagc: F6自动厚度控制设定值
    F7_agc_wssagc: F7自动厚度控制设定值
    F1_extthick: F1机架出口厚度
    F2_extthick: F2机架出口厚度
    F3_extthick: F3机架出口厚度
    F4_extthick: F4机架出口厚度
    F5_extthick: F5机架出口厚度
    F6_extthick: F6机架出口厚度
    F7_extthick: F7机架出口厚度
    F1_set_force: F1设定轧制力
    F2_set_force: F2设定轧制力
    F3_set_force: F3设定轧制力
    F4_set_force: F4设定轧制力
    F5_set_force: F5设定轧制力
    F6_set_force: F6设定轧制力
    F7_set_force: F7设定轧制力
    F1_set_bendforce: F1设定弯辊力
    F2_set_bendforce: F2设定弯辊力
    F3_set_bendforce: F3设定弯辊力
    F4_set_bendforce: F4设定弯辊力
    F5_set_bendforce: F5设定弯辊力
    F6_set_bendforce: F6设定弯辊力
    F7_set_bendforce: F7设定弯辊力
    F1_set_shift: F1窜辊设定
    F2_set_shift: F2窜辊设定
    F3_set_shift: F3窜辊设定
    F4_set_shift: F4窜辊设定
    F5_set_shift: F5窜辊设定
    F6_set_shift: F6窜辊设定
    F7_set_shift: F7窜辊设定
    F1_set_rollspeed: F1设定机架工作辊线速度
    F2_set_rollspeed: F2设定机架工作辊线速度
    F3_set_rollspeed: F3设定机架工作辊线速度
    F4_set_rollspeed: F4设定机架工作辊线速度
    F5_set_rollspeed: F5设定机架工作辊线速度
    F6_set_rollspeed: F6设定机架工作辊线速度
    F7_set_rollspeed: F7设定机架工作辊线速度
    F1_set_enttemp: F1设定机架入口温度
    F2_set_enttemp: F2设定机架入口温度
    F3_set_enttemp: F3设定机架入口温度
    F4_set_enttemp: F4设定机架入口温度
    F5_set_enttemp: F5设定机架入口温度
    F6_set_enttemp: F6设定机架入口温度
    F7_set_enttemp: F7设定机架入口温度
    F1_set_exttemp: F1设定机架出口温度
    F2_set_exttemp: F2设定机架出口温度
    F3_set_exttemp: F3设定机架出口温度
    F4_set_exttemp: F4设定机架出口温度
    F5_set_exttemp: F5设定机架出口温度
    F6_set_exttemp: F6设定机架出口温度
    F7_set_exttemp: F7设定机架出口温度
    F1_set_looperangle: F1机架间设定活套角度
    F2_set_looperangle: F2机架间设定活套角度
    F3_set_looperangle: F3机架间设定活套角度
    F4_set_looperangle: F4机架间设定活套角度
    F5_set_looperangle: F5机架间设定活套角度
    F6_set_looperangle: F6机架间设定活套角度
    F1_set_loopertension: F1活套设定张力
    F2_set_loopertension: F2活套设定张力
    F3_set_loopertension: F3活套设定张力
    F4_set_loopertension: F4活套设定张力
    F5_set_loopertension: F5活套设定张力
    F6_set_loopertension: F6活套设定张力
    flatall_min: 平直度全长最小值
    flatall_max: 平直度全长最大值
    symflatnessMeanALL: 对称平直度全长均值
    L2_FM_FLAT_100_FIRE: L2_FM_平直度命中率(头部)
    L2_FM_WEDEG1_FIRE: L2_FM_平直度命中率(全长)
    L2_FM_IMS_31: L2_FM_冷后头部100米对称平直度精度（34IU）
    L2_FM_IMS_32: L2_FM_冷后头部100米非对称平直度精度（34IU）
    L2_FM_IMS_33: L2_FM_冷后尾部100米对称平直度精度（34IU）
    L2_FM_IMS_34: L2_FM_冷后尾部100米非对称平直度精度（34IU）
    symflatness_head100: 头部100米对称平直度精度
    asymflatness_head100: 头部100米非对称平直度精度
    symflatness_tail100: 尾部100米对称平直度精度
    asymflatness_tail100: 尾部100米非对称平直度精度
    threadspeed: L2_FM_带钢穿带速度
    C1_ma_tension_ref: C1卷筒张力给定
    C3_ma_tension_ref: C3卷筒张力给定

